### ISSUE TITLE
Where can we find the repository for `proton-vpn-network-manager-wireguard`?

### ISSUE THREAD

**Issue by antermin** [ProtonVPN/python-proton-vpn-network-manager#3]
https://github.com/ProtonVPN/python-proton-vpn-network-manager/blob/dd9a7953cbe882ab63f90a4025e4ebef181c151e/rpmbuild/SPECS/package.spec#L37

https://github.com/ProtonVPN/python-proton-vpn-network-manager/blob/dd9a7953cbe882ab63f90a4025e4ebef181c151e/debian/control#L12

Both build scripts refer to `python3-proton-vpn-network-manager-wireguard`, but I am unable to find the corresponding repository.

It would be great if ProtonVPN can publish it so that we can try using WireGuard with the official ProtonVPN app on Linux.

**Comment by calexandru2018** [comment]
Hey @antermin 

WireGuard is being developed internally, thus the references. We're finishing the touch-up's on the kill switch and it should be in beta (if everything goes well) in the next two weeks. To note that the WireGuard protocol will still be flagged as experimental.

**Comment by calexandru2018** [comment]
Hey @antermin , I'll be publishing them asap but do not that we're in the works of merging repos/packages into another. For example, core-api [now has 4 sub-modules](https://github.com/ProtonVPN/python-proton-vpn-api-core/tree/master/proton/vpn):
- core (which already existed there)
- connection which replaces https://github.com/ProtonVPN/python-proton-vpn-connection
- killswitch/interface which replaces https://github.com/ProtonVPN/python-proton-vpn-killswitch
- session which replaces https://github.com/ProtonVPN/python-proton-vpn-session

We'll be working on further refactoring this, so it's easier to maintain and push updates.

**Comment by calexandru2018** [comment]
Done:
- https://github.com/ProtonVPN/python-proton-vpn-network-manager-wireguard
- https://github.com/ProtonVPN/python-proton-vpn-killswitch-network-manager-wireguard

**Comment by molaeiali** [comment]
> Done:
> 
>     * https://github.com/ProtonVPN/python-proton-vpn-network-manager-wireguard
> 
>     * https://github.com/ProtonVPN/python-proton-vpn-killswitch-network-manager-wireguard

after installing these, I still only have openvpn options inside the application settings > protocol, shouldn't this add wireguard as an option?

**Comment by calexandru2018** [comment]
@molaeiali well tbh the FF are already enabled to anyone, so unless you're missing the packages I don't see a reason why it's not showing.

Also @antermin even though it can be bypassed, it often recommended  not to do so as we often have these FF so the app does not break for everybody.

>  (while I get IPv6 if I use OpenVPN, it looks like ProtonVPN has rolled out IPv6 for a lot of servers).
Yeah also, after WG our goal is to work on IPv6, but since it depends on multiple teams lets see how this goes.

> Also, there may be some slight hiccups when connecting via WireGuard, as sometimes it will timeout (fail to connect and I have to choose another location / server) or disconnect suddenly. I don't encounter these issues as often as WireGuard if I connect via OpenVPN.
Even though WireGuard is experimental _it should be stable_ nonetheless. We hope that withing 1-3 weeks time  frame we can improve this, as we have another package coming (in Rust) that should help to iron out any issues with WG protocol.

**Comment by molaeiali** [comment]
@antermin I couldn't enable beta mode, can you provide more instructions about what I'm supposed to do?

@calexandru2018 I think the package is installed correctly, I'm just getting this log related to wireguard
```
2024-08-01T12:00:46.830703 | proton.vpn.backend.linux.networkmanager.protocol.wireguard.local_agent.fallback_local_agent:31 | WARNING | Fallback local agent was loaded.
```
Is this bad that it's falling back? should it use external agent? if yes, does it need to have some binaries available in the system maybe (wg-quick for example)

**Comment by calexandru2018** [comment]
@molaeiali the beta flag is something entirely different, so don't worry about it. We've recently implemented so that people on Fedora/Debian/Ubuntu can easily switch between beta and stable. But WireGuard is just behind a FF and is nothing related to "beta", that might've been a misunderstanding.

> Is this bad that it's falling back? should it use external agent? if yes, does it need to have some binaries available in the system maybe (wg-quick for example)

As I've said above we're working on a Rust package that should improve WG connectivity, until then (and actually it's been like that since we introduce the protocol) you'll be using the fallback version, which does not depend on this external Rust package that we're working on. It should though be released "soon" as I've also mentioned above.

**Comment by calexandru2018** [comment]
@antermin the FF are things that users don't have control over, that is provided by the API. We've already enabled 100% for WG and we're gradually rolling out the beta toggle (so not everybody will have it atm). For WG you don't have to do anything, as long as you have all the necessary packages installed, it should appear automatically in the Settings -> Protocol window.
